// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljpenesnfveiqjiepqob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqcGVuZXNuZnZlaXFqaWVwcW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDE2NzIsImV4cCI6MjA2MDI3NzY3Mn0.gGkcBSoyFzKdTIaXAUdDNhYNOZWtZ8RyRcl27hQ0jGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);